accounts/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import *
from products.views import UserProductHistoryView
app_name = "account"

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^login/$', RedirectView.as_view(url='browse')),
    # url(r'^login/$', login_view, name='login'),
    url(r'^register/guest/$', guest_register_view, name='guestregister'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^$', AccountHomeView.as_view(), name='accounthome'),
    url(r'^history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),

]

carts/urls.py
from django.conf.urls import url

from .views import(
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    adres_ekle,
    cart_q_add_view,
    cart_q_remove_view
    )

urlpatterns = [

    url(r'^$',cart_home, name='homecart'),
    url(r'^checkout/$', checkout_home, name='checkoutcart'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='updatecart'),
    url(r'^adres-ekle/$', adres_ekle, name='adrescart'),
    url(r'^add-q/$', cart_q_add_view, name='addq'),
    url(r'^remove-q/$', cart_q_remove_view, name='removeq'),

]

accounts/models.py
from django.db import models

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)

class UserManager(BaseUserManager):
    def create_user(self, email, username=None, full_name=None,  password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Bir e-mail adresi olmalı")
        if not password:
            raise ValueError("Bir şifre olmalı")

        user_obj = self.model(
            email=self.normalize_email(email),
            full_name=full_name,
            username=username,
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, username=None, full_name=None, password=None):
        user = self.create_user(
            email,
            username=username,
            full_name=full_name,
            password=password,
            is_staff=True
        )
        return user
    def create_superuser(self, email, username=None, full_name=None, password=None):
        user = self.create_user(
            email,
            username=username,
            full_name=full_name,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    full_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Tam isim")
    username = models.CharField(max_length=254, verbose_name='Kullanıcı Adı', null=True, blank=True, unique=True)
    first_name = models.CharField(max_length=254, verbose_name='Ad', null=True,blank=True)
    last_name = models.CharField(max_length=254, verbose_name='Soyad', null=True,blank=True)
    active = models.BooleanField(default=True) #can login
    staff = models.BooleanField(default=False) #staff user
    admin = models.BooleanField(default=False) #superuser
    timestamp = models.DateTimeField(auto_now_add=True)
    # confirm = models.BooleanField(default=False)
    # confirmed_date = models.DateTimeField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username',] #['full_name']

    objects = UserManager()

    def __str__(self):
        return self.email
    def get_username(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, obj=None):
        return True
    def has_module_perms(self, app_label):
        return True

    @property
    def name(self):
        return self.username

    @property
    def is_staff(self):
        if self.is_admin:
            return True
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active



class GuestEmail(models.Model):
    email = models.EmailField()
    active = models.BooleanField(default=True)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
# from .backend import EmailBackend
# from django.core.validators import validate_email
# from django.contrib.auth import get_user_model
# from django.contrib.auth.backends import ModelBackend
User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Şifreler Eşleşmiyor")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class GuestForm(forms.Form):
    email = forms.EmailField()




class LoginForm(forms.Form):

    username = forms.CharField(max_length=100,label='',
                                   widget=forms.TextInput(
                                       attrs={'placeholder': 'Kullanıcı Adı ya da E-Posta'}
                                   ))
    password = forms.CharField(max_length=100, label='',
                                   widget=forms.PasswordInput(
                                       attrs={'placeholder': 'Şifre'}
                                   ))




    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            try:
                user = authenticate(username=username, password=password)
            except User.DoesNotExist:
                raise forms.ValidationError("Kullanıcı Adını veya Şifreyi Yanlış Girdiniz!")

            if not user:
                raise forms.ValidationError("Kullanıcı Adını veya Şifreyi Yanlış Girdiniz!")


        return super(LoginForm, self).clean()

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    # username = forms.CharField(max_length=254, label='Kullanıcı Adı')
    password1 = forms.CharField(label='Şifre', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Şifre(Tekrar)', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', "last_name", 'email',)
        # fields['username'].widget.attrs({'placeholder': 'Kullanıcı Adı'})

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Şifreler Eşleşmiyor")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        # user.active = False
        if commit:
            user.save()
        return user





# class RegisterForm(forms.ModelForm):
#     username = forms.CharField(max_length=254,label='Kullanıcı Adı')
#     first_name = forms.CharField(max_length=254,label='Ad')
#     last_name = forms.CharField(max_length=254,label='Soyad')
#
#     password1 = forms.CharField(max_length=100, label='Şifre',widget=forms.PasswordInput)
#     password2= forms.CharField(max_length=100, label='Şifre Doğrulama',widget=forms.PasswordInput)
#     email = forms.EmailField(max_length = 254,widget=forms.EmailInput)
#
#
#
#     class Meta:
#
#         model = User
#
#         fields = [
#             'username',
#             'first_name',
#             'last_name',
#             'password1',
#             'password2',
#             'email',
#             ]
#     def clean_password2(self):
#         password1 = self.cleaned_data.get('password1')
#         password2 = self.cleaned_data.get('password2')
#
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError('Şifreler Eşleşmiyor')
#         return password2

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #
    #     if validate_email(email):
    #         email=True
    #     else:
    #         email=False
    #
    #     return email

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, GuestForm
from .models import GuestEmail
from .signals import user_logged_in
from django.contrib.auth import authenticate, login, logout
from django.utils.http import is_safe_url
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, FormView, DetailView


# @login_required
# def account_home_view(request):
#     return render(request, 'accounts/home.html')

# class LoginRequiredMixin(object):
#     @method_decorator(login_required)
#     def dispatch(self, request, *args, **kwargs):
#         return super(LoginRequiredMixin, self).dispatch(self, request, *args, **kwargs)


class AccountHomeView(LoginRequiredMixin,DetailView):
    template_name = 'accounts/home.html'

    def get_object(self):
        return self.request.user


def guest_register_view(request):
    form = GuestForm(request.POST or None)
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if form.is_valid():
        email = form.cleaned_data.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect('home')

    return render(request, "accounts/form.html", {"form": form, 'title': 'Giriş Yap'})

class LoginView(FormView):
    form_class = LoginForm
    template_name = "accounts/form.html"
    success_url = '/browse'


    def form_valid(self, form):
        request = self.request
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None

        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            user_logged_in.send(user.__class__, instance=user, request=request)
            try:
                del request.sessinon['guest_email_id']
            except:
                pass
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect('browse')

        return super(LoginView, self).form_invalid(form)






class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = "accounts/form1.html"
    success_url = '/browse'



    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)

        return redirect('browse')

def logout_view(request):
    logout(request)
    return redirect('browse')

    # def login_v(self):
    #     request = self.request
    #     form = RegisterForm(request.POST or None)
    #     username = form.cleaned_data.get('username')
    #     password = form.cleaned_data.get('password')
    #     user = authenticate(username=username, password=password)
    #     if user is not None:
    #         login(request, user)
    #
    #     return super(RegisterView, self)


    # def register(self):
    #     request = self.request
    #     form = RegisterForm(request.POST or None)
    #
    #     return render(request, "accounts/form.html", {"form": form,'title': 'Üye Ol'})


# User = get_user_model()
# def register_view(request):
#     form = RegisterForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         # user = form.save(commit=False)
#         # password = form.cleaned_data.get('password1')
#         # user.set_password(password)
#         # user.save()
#         # new_user = authenticate(first_name=user.first_name, password=password)
#         # login(request, new_user)
#
#     return render(request, "accounts/form.html", {"form": form, 'title': 'Üye Ol'})
#



# def login_view(request):
#     form = LoginForm(request.POST or None)
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         username = form.cleaned_data.get('username')
#         password = form.cleaned_data.get('password')
#         user = authenticate(username=username, password=password)
#         if user is not None:
#             login(request, user)
#             try:
#                 del request.sessinon['guest_email_id']
#             except:
#                 pass
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect('home')
#     return render(request, "accounts/form.html", {"form": form,'title':'Giriş Yap'})

home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    # if request.user.is_authenticated():
    #     context = {
    #         'isim': 'Barış'
    #     }
    # else:
    #     context = {
    #         'isim': 'Misafir Kullanıcı'
    #     }
    return render(request, 'home.html', {})

def about_page(request):
    return render(request, 'home.html', {})


def contact_page(request):
    return render(request, 'contact.html', {})

templates/accounts/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <style>
body {
    background-image: url(/static/img/wow.jpg);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
}
    </style>
    {% if not request.user.is_authenticated  %}
        <div class="padd">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="uye-log">
                    <h1>Giriş Yap</h1>
                    <form method="POST" enctype="multipart/form-data"><br>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary" type="submit" value="Giriş Yap">
    {#                    <input class="btn btn-primary" type="submit" value="{{ title }}">#}
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>

        {% else %}
         <div class="container">
             <div class="padd2">
                <a href="{% url "browse" %}"><h1>Ana sayfaya dön</h1></a>
              </div>
        </div>
        {% endif %}

{% endblock %}

templates/accounts/form1.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
        <style>
body {
    background-image: url(/static/img/wow3.jpg);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
}
    </style>
    {% if not request.user.is_authenticated  %}
    <div class="padd">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="uye-log">
                <h1>Üye Ol</h1>
                <form method="POST" enctype="multipart/form-data"><br>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Üye Ol">
{#                    <input class="btn btn-primary" type="submit" value="{{ title }}">#}
                </form>
            </div>
        </div>
    </div>
    </div>
</div>
    {% else %}
         <div class="container">
             <div class="padd2">
                <a href="{% url "browse" %}"><h1>Ana sayfaya dön</h1></a>
              </div>
        </div>
    {% endif %}

{% endblock %}

templates/accounts/home.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">

            <div class="padd2">
               <div style="margin-left: 20px; margin-bottom: 20px" ><h1>Hesap</h1><hr/> <h2>{{ request.user.name }}</h2></div>
                <div class="col-md-3">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Destek</h3>
                      </div>
                      <div class="panel-body">
                          <div class="list-group">
                              <a class="list-group-item" href="{% url 'about' %}">Hakkında</a>
                              <a class="list-group-item" href="{% url 'contact' %}">İletişim</a>
                          </div>

                      </div>
                    </div>
                    </div>

                     <div class="col-md-3">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Fatura</h3>
                      </div>
                      <div class="panel-body">
                           <div class="list-group">
                               <a class="list-group-item" href="{% url 'orders:list' %}">Siparişler</a>
                              <a class="list-group-item" href="#">Adresler</a>

                          </div>
                      </div>
                    </div>
                     </div>
                      <div class="col-md-3">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Profil</h3>
                      </div>
                      <div class="panel-body">
                             <div class="list-group">
                               <a class="list-group-item" href="#">Bilgilerini Güncelle</a>
                               <a class="list-group-item" href="#">Şifre Değiştir</a>


                          </div>

                      </div>
                    </div>
                      </div>

                 <div class="col-md-3">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Tercihler</h3>
                      </div>
                      <div class="panel-body">
                             <div class="list-group">
                                 <a class="list-group-item" href="#">Email</a>
                                <a class="list-group-item" href="{% url 'marketing-pref' %}">Email pazarlama tercihleri</a>

                          </div>

                      </div>
                    </div>
                      </div>


                    <div class="col-md-3">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Geçmiş</h3>
                      </div>
                      <div class="panel-body">
                            <a class="list-group-item" href="{% url 'account:user-product-history' %}">Görüntülenen Ürünler</a>
                      </div>
                    </div>
                      </div>

                </div>
            </div>

    </div>



{% endblock %}