carts/urls.py
from django.conf.urls import url

from .views import(
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    adres_ekle,
    cart_q_add_view,
    cart_q_remove_view
    )

urlpatterns = [

    url(r'^$',cart_home, name='homecart'),
    url(r'^checkout/$', checkout_home, name='checkoutcart'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='updatecart'),
    url(r'^adres-ekle/$', adres_ekle, name='adrescart'),
    url(r'^add-q/$', cart_q_add_view, name='addq'),
    url(r'^remove-q/$', cart_q_remove_view, name='removeq'),

]

products/urls.py
from django.conf.urls import url

from .views import(
    ProductListView,
    ProductDetailSlugView,
    )

app_name = "products"

urlpatterns = [

    url(r'^$',ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

siparis/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin
from home.views import (home_view, about_page, contact_page)
from analytics.views import SalesView, SalesAjaxView
from addresses.views import (checkout_address_create_view, checkout_address_reuse_view)
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from carts.views import cart_detail_api_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home_view, name='home'),
    url(r'^browse/$',home_view, name='browse'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^about/$',about_page,name='about'),
    url(r'^contact/$',contact_page,name='contact'),
    url(r'^analytics/sales/$',SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^accounts/', RedirectView.as_view(url='/account/login')),
    url(r'^account/', include('accounts.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^api/cart/$', cart_detail_api_view, name="api-cart"),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
# from carts.models import CartItem
import random
import os
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from siparis.utils import unique_slug_generator
from django.urls import reverse

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)

    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename,
                                                             final_filename=final_filename)

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(price__icontains=query) |
                Q(tag__title__icontains=query)
                )
        return self.filter(lookups).distinct()


class ProdocutManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self.db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):

        return self.get_queryset().featured()

    def get_by_id(self,id):
        qs = self.get_queryset().filter(id=id)

        if qs.count() == 1:
            return qs.first()

        return None

    def search(self, query):
        return self.get_queryset().active().search(query)



class Product(models.Model):

    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField()
    category = models.CharField(max_length=120, default='')
    price = models.DecimalField(decimal_places=2, max_digits=20, default=12)
    # quantity = models.ManyToManyField(CartItem)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProdocutManager()

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug":self.slug})



    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title
    @property
    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from carts.models import Cart
from .models import Product
from tags.models import Tag
from analytics.mixins import ObjectViewedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class ProductFeaturedListView(ListView):
    # queryset = Product.objects.all()
    template_name = "products/list.html"


    def get_queryset(self, *args, **kwargs):
        request = self.request

        return Product.objects.all().featured()

class ProductFeaturedDeatilView(ObjectViewedMixin,DetailView): #ObjectViewedMixin,
    queryset = Product.objects.featured()
    template_name = "products/featured-detail.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request

        return Product.objects.all().featured()

class UserProductHistoryView(LoginRequiredMixin,ListView):
    # template_name = "products/user-history.html"
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super(UserProductHistoryView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        views = request.user.objectviewed_set.by_model(Product, model_queryset=True) #.filter(content_type__name='product')
        # viewed_ids = [x.object_id for x in views]
        # Product.objects.filter(pk__in=viewed_ids)
        return views


class ProductListView(ListView):
    template_name = "products/list.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     return context

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        # tag = Tag.objects.get(title='çorba')
        # tag2 = Tag.objects.get(title='tatlı')
        # return tag.products.all()
        return Product.objects.all()



# def product_list_view(request):
#     tag = Tag.objects.get(title='çorba')
#     a = tag.products.all()
#     # tag_queryset = Tag.objects.get_queryset()
#     # for tag_obj in tag_queryset:
#     #     obj = tag_obj.products.all()
#
#     queryset = Product.objects.all()
#     # tag_query_set = Tag.objects.all()
#     # corba_set = Tag.objects.get(title='çorba')
#
#
#     context = {
#         'object_list': 'a',
#         # 'tag_list':tag_query_set,
#         # 'corba_list': corba_set
#         # 'corba_list': a
#
#     }

    # return render(request, 'products/list.html', {})


class ProductDetailSlugView(ObjectViewedMixin, DetailView): #ObjectViewedMixin,
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context


    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        # instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Bulunamadı..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Garip bir istek..")

        # object_viewed_signal.send(instance.__class__, instance=instance, request=request)

        return instance

class ProductDetailView(ObjectViewedMixin, DetailView): #ObjectViewedMixin,
    # queryset = Product.objects.all()
    template_name = "products/detail.html"
    def get_context_data(self, *args, **kwargs):

        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        return context


    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Ürün mecvut eğil")
        return instance

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #
    #     return Product.objects.filter(pk=pk)



def product_detail_view(request, pk=None, *args, **kwargs ):
    # instance = Product.objects.get(pk=pk, featured=True)
    # instance = get_object_or_404(Product, pk=pk, featured=True)
    # try:
    #     instance = Product.objects.get(id=pk)
    #
    # except Product.DoesNotExist:
    #     raise Http404("Ürün mecvut eğil")
    #
    # except:
    #     print("NOpe")

    instance = Product.objects.get_by_id(pk)

    if instance is None:
        raise Http404("Ürün mecvut eğil")

    # print(instance)
    #
    # qs = Product.objects.filter(id=pk)
    #
    # if qs.exists() and qs.count() == 1:
    #     instance = qs.first()
    # else:
    #     raise Http404("Ürün mecvut eğil")

    context = {
        'object': instance

        }

    return render(request, 'products/detail.html', context)

templates/products/snippets/card-corba.html
<li class="item soup">
    {% if instance.image %}
        <a rel="prettyPhoto[Group]" href="{{ instance.get_absolute_url }}?iframe=true&height=515&width=450&">
        <img class="img-responsive" src="{{ instance.image.url }}" >
    {% endif %}
        <div class="menu-desc text-center">
            <span>
                <h3 class="sabit-desc">{{ instance.title }}</h3>
                <h3 class="hareket-desc">{{ instance.title }}</h3>
                <p>Fiyat: {{ instance.price }} TL</p>
            </span>
        </div>
    </a>
        <div class="spt-ynt">{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}</div>
</li>

templates/products/snippets/card-ekstra.html
<li class="item dessert">
    {% if instance.image %}
        <a rel="prettyPhoto[Group]" href="{{ instance.get_absolute_url }}?iframe=true&height=515&width=450&">
        <img class="img-responsive" src="{{ instance.image.url }}" >
    {% endif %}
        <div class="menu-desc text-center">
            <span>
                <h3 class="sabit-desc">{{ instance.title }}</h3>
                <h3 class="hareket-desc">{{ instance.title }}</h3>
                <p>Fiyat: {{ instance.price }} TL</p>
            </span>
        </div>
    </a>
        <div class="spt-ynt">{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}</div>
</li>

templates/products/snippets/card-et.html
{#{% extends 'base.html' %}#}
{#{% block body %}#}

{#<div class="card">#}
{##}
{#<div class="card-title">#}
{#    <h5 class="card-title">{{ instance.title }}</h5>#}
{#</div>#}
{#    <div class="card-img">#}
{#    {% if instance.image %}#}
{#        <a href="{{ instance.get_absolute_url }}">#}
{#           <a rel="prettyPhoto[Group]" href="{{ instance.get_absolute_url }}?iframe=true&height=515&width=450&"> <img class="card-img-top" src="{{ instance.image.url }}" alt=""></a>#}
{#        </a>#}
{#    {% endif %}#}
{#    </div>#}
{##}
{#  <div class="card-body">#}
{##}
{#      <p class="card-text">Fiyat: {{ instance.price|linebreaksbr|truncatewords:20 }} TL</p>#}
{##}
{##}
{#  </div>#}
{##}
{##}
{#    <div class="card-button">#}
{#    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">Görüntüle</a>#}
{#        {% include 'products/snippets/update-cart.html' with product=instance cart=cart %}#}
{#    <a href="{% url 'products:detail' slug=instance.slug %}" class="btn btn-warning">URL shorcut</a>#}
{#  </div>#}
{##}
{#</div>#}

{#{% endblock %}#}
<li class="item main-course">
    {% if instance.image %}
        <a rel="prettyPhoto[Group]" href="{{ instance.get_absolute_url }}?iframe=true&height=515&width=450&">
        <img class="img-responsive" src="{{ instance.image.url }}" >
    {% endif %}
        <div class="menu-desc text-center">
            <span>
                <h3 class="sabit-desc">{{ instance.title }}</h3>
                <h3 class="hareket-desc">{{ instance.title }}</h3>
                <p>Fiyat: {{ instance.price }} TL</p>
            </span>
        </div>
    </a>
        <div class="spt-ynt">{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}</div>
</li>

templates/products/snippets/card-salata.html
<li class="item extra-product">
    {% if instance.image %}
        <a rel="prettyPhoto[Group]" href="{{ instance.get_absolute_url }}?iframe=true&height=515&width=450&">
        <img class="img-responsive" src="{{ instance.image.url }}" >
    {% endif %}
        <div class="menu-desc text-center">
            <span>
                <h3 class="sabit-desc">{{ instance.title }}</h3>
                <h3 class="hareket-desc">{{ instance.title }}</h3>
                <p>Fiyat: {{ instance.price }} TL</p>
            </span>
        </div>
    </a>
        <div class="spt-ynt">{% include 'products/snippets/update-cart.html' with product=instance cart=cart %}</div>
</li>

templates/products/snippets/update-cart.html
 <form class="form-product-ajax" class="form" method="POST" action="{% url 'cart:updatecart' %}" data-endpoint="{% url 'cart:updatecart' %}"> {% csrf_token %}
    <input class="cart-item-product-id" type="hidden" name="product_id" value="{{ product.id }}"/>
{#    {% if in_cart %}#}
{#        <button type="submit" class="btn btn-link btn-sm" style="padding:0; cursor:pointer;" >Sepetten Çıkar</button>#}
{#    {% else %}#}
{##}
{#    {% endif %}#}
        <span class="submit-span">
        {% if product in cart.products.all %}
              <button type="submit" class="btn btn-sm">Sepetten Çıkar</button>
        {% else %}
               <button type="submit" class="btn btn-success">Sepete Ekle</button>
        {% endif %}
        </span>

    </form>