accounts/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from .views import *
from products.views import UserProductHistoryView
app_name = "account"

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^login/$', RedirectView.as_view(url='browse')),
    # url(r'^login/$', login_view, name='login'),
    url(r'^register/guest/$', guest_register_view, name='guestregister'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    # url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^$', AccountHomeView.as_view(), name='accounthome'),
    url(r'^history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),

]

carts/urls.py
from django.conf.urls import url

from .views import(
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    adres_ekle,
    cart_q_add_view,
    cart_q_remove_view
    )

urlpatterns = [

    url(r'^$',cart_home, name='homecart'),
    url(r'^checkout/$', checkout_home, name='checkoutcart'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='updatecart'),
    url(r'^adres-ekle/$', adres_ekle, name='adrescart'),
    url(r'^add-q/$', cart_q_add_view, name='addq'),
    url(r'^remove-q/$', cart_q_remove_view, name='removeq'),

]

products/urls.py
from django.conf.urls import url

from .views import(
    ProductListView,
    ProductDetailSlugView,
    )

app_name = "products"

urlpatterns = [

    url(r'^$',ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

siparis/urls.py
from django.conf.urls import (url, include)
from django.contrib import admin
from home.views import (home_view, about_page, contact_page)
from analytics.views import SalesView, SalesAjaxView
from addresses.views import (checkout_address_create_view, checkout_address_reuse_view)
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from carts.views import cart_detail_api_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home_view, name='home'),
    url(r'^browse/$',home_view, name='browse'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^about/$',about_page,name='about'),
    url(r'^contact/$',contact_page,name='contact'),
    url(r'^analytics/sales/$',SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^accounts/', RedirectView.as_view(url='/account/login')),
    url(r'^account/', include('accounts.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^api/cart/$', cart_detail_api_view, name="api-cart"),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    # if request.user.is_authenticated():
    #     context = {
    #         'isim': 'Barış'
    #     }
    # else:
    #     context = {
    #         'isim': 'Misafir Kullanıcı'
    #     }
    return render(request, 'home.html', {})

def about_page(request):
    return render(request, 'home.html', {})


def contact_page(request):
    return render(request, 'contact.html', {})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}İncir Ege Mutfağı{% endblock %}</title>
   <link rel="shortcut icon" href="{% static 'img/as.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/pricing.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

</head>
<body>

    {% include 'messages.html' %}
    {% include "header.html" %}

{#    {% include 'middle.html' %}#}

    {% block body %}
    {% endblock %}

{% block javascript %}
    <script src="{% static "js/jquery-1.11.2.min.js" %}"></script>
    <script src="{% static "js/jquery.flexslider.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.mixitup.min.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>
    <script src="{% static "js/jquery.validate.js" %}"></script>
    <script src="{% static "js/jquery.hoverdir.js" %}"></script>
    <script src="{% static "js/jQuery.scrollSpeed.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>

{#    jquery confirm #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

{#    Chart Js#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

    {# Django Secure Ajax Js#}
    <script src="{% static "js/csrf.ajax.js" %}"></script>
    <script src="{% static "js/jquery.prettyPhoto.js" %}"></script>
    {#    eCommerce Sales Data- Js#}
    <script src="{% static "js/ecommerce.sales.js" %}"></script>

    {#    eCommerce-Js#}
    <script src="{% static "js/ecommerce.js" %}"></script>
        <script type="text/javascript">
		$(document).ready(function(){
        $("a[rel^='prettyPhoto[Group]']").prettyPhoto({animationSpeed:'slow',theme:'facebook'});
		});</script>

    <script type="text/javascript">
		$(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({animationSpeed:'slow',theme:'facebook'});
		});
    </script>
{% endblock %}
</body>
</html>

templates/contact.html
<style>
   nav#template-navbar {
	display: none;
}
</style>
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
       <div id="form-main">
<div id="form-div">
    <h2>İletişim Sayfası</h2>
<form class="form" id="form1">

<p class="name">
<input name="name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="İsim" id="name" />
</p>

<p class="email">
<input name="email" type="text" class="validate[required,custom[email]] feedback-input" id="email" placeholder="Eposta" />
</p>

<p class="text">
<textarea name="text" class="validate[required,length[6,300]] feedback-input" id="comment" placeholder="Yazınız"></textarea>
</p>


<div class="submit">
<input type="submit" value="GÖNDER" id="button-blue"/>
<div class="ease"></div>
</div>
</form>
</div>
           </div></div>

{% endblock %}

templates/header.html
{% url 'account:accounthome' as account_url %}
{% url 'account:logout' as logout_url %}
{% url 'account:register' as register_url %}
{% url 'account:login' as login_url %}
{% url 'sales-analytics' as sales_analytics_url %}
{% url 'products:list' as product_list_url %}
<!--== 4. Navigation ==-->
        <nav id="template-navbar" class="navbar navbar-default custom-navbar-default navbar-fixed-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                     <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
{#                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#Food-fair-toggle">#}
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'browse' %}">
                        <img id="logo" src="/static/img/logo1.png" class="logo img-responsive">
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="Food-fair-toggle">
                    <ul class="nav navbar-nav navbar-right">
                    <li id="small-search">
                        <a>
                        <form class="search-form" role="search" method="GET" action="{% url 'search:query' %}">
                        <div id="small-group" class="input-group">
                        <input class="form-control-2" type="text" name="q" placeholder="Yemek Ara" value="{{ request.GET.q }}" >
                        </div></form></a>
                    </li>
                        {% if request.user.is_staff%}
                        <li><a class="{% if request.path == sales_analytics_url%}active{%endif %}"  href="{{ sales_analytics_url }}">Analiz</a></li>
                        {% endif %}
                        <li><a class="{% if request.path == product_list_url%}active{%endif %}" href="{{ product_list_url }}">Yemekler</a></li>


                        <li>
                             <a rel="prettyPhoto-Sepet" href="{% url 'cart:homecart' %}?iframe=true&height=400&">
                                <img src="/static/img/shopping-cart.png"><span class="navbar-cart-count">
                                {{ request.session.cart_items }}</span>
                             </a>
                        </li>



                        <li><a rel="prettyPhoto" class="navbar-link" href="{% url 'contact' %}?iframe=true&height=480&width=400">İletişim</a></li>
                        {% if not request.user.is_authenticated  %}
                            <li><a class="{% if request.path == login_url%}active{%endif %}"  href="{{ login_url }}">Giriş Yap</a></li>
                            <li><a class="{% if request.path == register_url%}active{%endif %}" href="{{ register_url }}">Üye Ol</a></li>
                        {% else %}

                            <li>

                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.name }}<span class="caret"></span></a>
                                  <ul class="dropdown-menu">
                                        <li><a id="top-tog" class="{% if request.path == account_url%} active{%endif %}" href="{{ account_url }}">Hesap</a></li>
                                        <li><a href="#">Faturalama</a></li>
                                        <li><a href="#">Tercihler</a></li>
                                        <li><a href="#">Geçmiş</a></li>
{#                                        <li role="separator" class="divider"></li>#}
{#                                        <li><a href="#">Separated link</a></li>#}
                                        <li role="separator" class="divider"></li>
                                        <li id="bottom-tog"><a class="{% if request.path == logout_url%}active{%endif %}" href="{{ logout_url }}">Çıkış Yap</a></li>
                                  </ul>
                            </li>
                        {% endif %}
                    </ul>
                {# <!-- Arama Çubuğu -->#}

                <form class="navbar-form search-form" role="search" method="GET" action="{% url 'search:query' %}">
                <div id="big-group" class="input-group">

                    <input class="form-control" type="text" name="q" placeholder="Yemek Ara" value="{{ request.GET.q }}" >

                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Ara</button>
{#                        <input class="btn btn-default" type="submit" value="Ara">#}
                    </span>
                </div>
            </form>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.row -->
        </nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

{% block body %}

    <!--== 5. Header ==-->
        <section id="header-slider">
            <div class="item">
                <div class="container">
                    <div class="header-content">
                        <h1 class="header-title">Lezzetli Sıcak Yemekler</h1>
                        <p class="header-sub-title"></p>
                    </div> <!-- /.header-content -->
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <div class="header-content">
                        <h1 class="header-title">En Taze Malzemeler</h1>
                        <p class="header-sub-title"></p>
                    </div> <!-- /.header-content -->
                </div>
            </div>
            <div class="item">
                <div class="container">
{#                    <div class="header-content /*text-right pull-right*/">#}
                    <div class="header-content">
                        <h1 class="header-title">En Leziz Baharatlar</h1>
                        <p class="header-sub-title"></p>
                    </div> <!-- /.header-content -->
                </div>
            </div>
        </section>

        <!--== 6. About us ==-->
        <section id="about" class="about">
            <img src="/static/img/about_color.png" class="img-responsive section-icon hidden-sm hidden-xs">
            <div class="wrapper">
                <div class="container-fluid">
                    <div class="row dis-table">
                        <div class="hidden-xs col-sm-6 section-bg about-bg dis-table-cell">

                        </div>
                        <div class="col-xs-12 col-sm-6 dis-table-cell">
                            <div class="section-content">
                                <h2 class="section-content-title">Hakkımızda</h2>
                                <p class="section-content-para">
                                    Astronomy compels the soul to look upward, and leads us from this world to another.  Curious that we spend more time congratulating people who have succeeded than encouraging people who have not. As we got further and further away, it [the Earth] diminished in size.
                                </p>
                                <p class="section-content-para">
                                    beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.  Where ignorance lurks, so too do the frontiers of discovery and imagination.
                                </p>
                            </div> <!-- /.section-content -->
                        </div>
                    </div> <!-- /.row -->
                </div> <!-- /.container-fluid -->
            </div> <!-- /.wrapper -->
        </section> <!-- /#about -->

    <!--== 10. Our Breakfast Menu ==-->
        <section id="breakfast" class="breakfast">
            <img class="img-responsive section-icon hidden-sm hidden-xs" src="/static/img/bread_black.png">
            <div class="wrapper">
                <div class="container-fluid">
                    <div class="row dis-table">
                        <div class="col-xs-6 col-sm-6 dis-table-cell color-bg">
                            <h2 class="section-title">Our Breakfast Menu</h2>
                        </div>
                        <div class="col-xs-6 col-sm-6 dis-table-cell section-bg">

                        </div>
                    </div> <!-- /.dis-table -->
                </div> <!-- /.row -->
            </div> <!-- /.wrapper -->
        </section> <!-- /#breakfast -->

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif%}